name: Monthly End-of-Life Report

on:
  schedule:
    - cron: '0 0 1 * *' # Runs on the first day of every month at midnight UTC
  workflow_dispatch:

jobs:
  generate-and-send-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Report Script
      env:
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      run: ruby generate_report.rb
